### ISSUE TITLE
http_post doesn't seem to fire

### ISSUE THREAD

**Issue by aulneau** [hirosystems/chainhook#211]
running this command:
```sh
 chainhook predicates scan ./chainhooks/stx-lock.json --mainnet
```

with this predicate:

```json
{
  "chain": "stacks",
  "uuid": "1",
  "name": "STX lock events",
  "version": 1,
  "networks": {
    "mainnet": {
      "if_this": {
        "scope": "stx_event",
        "actions": ["lock"]
      },
      "then_that": {
        "http_post": {
          "url": "http://localhost:8787/api/v1/chainhooks",
          "authorization_header": "Bearer cn389ncoiwuencr"
        }
      },
      "start_block": 0,
      "end_block": 32282
    }
  }
}
```

gives this output:

```
...
Hit at block 32117
Hit at block 32143
Hit at block 32144
Hit at block 32146
Hit at block 32173
Hit at block 32178
Hit at block 32180
Hit at block 32182
Hit at block 32192
Hit at block 32201
Hit at block 32215
Hit at block 32244
Hit at block 32246
Hit at block 32249
Hit at block 32254
Hit at block 32282
```

but no POSTing to the url provided. (the url is tested to work correctly)

**Comment by lgalabru** [comment]
Hey @aulneau! Thanks for your feedbacks, this particular issue should be fixed in the latest `main` branch.
The "previous version" of chainhooks - more stable - is still available in the `clarinet#main` repo: https://github.com/hirosystems/clarinet/tree/main/components/chainhook-node. The migration to this repo will be official once `clarinet#develop` merges into `main`.
The version present in this repo does outline the incoming evolutions of chainhooks (schemas, developer experience, etc) but it's pretty bleeding edge, and I will need a few days to stabilize things here.
Thank you for bearing with me!
