### ISSUE TITLE
How to do it?

### ISSUE THREAD

**Issue by echoWeb3** [hirosystems/chainhook#221]
Sorry, I am a btc novice, I have already installed the project in the normal link. Now I need to get the information of the btc ordinal in real time to deploy this git library: https://github.com/hirosystems/ordinals-api

What should I do? If you have time, I hope you can give me an answer with more words, thank you!

**Comment by lgalabru** [comment]
Hi @echoWeb3!
As soon as signaling through bitcoind is implemented, we will publish more documentation, but until then, you ll need to run both a bitcoind node and a stacks-node. As a consequence, running a `chainhook-node` is a bit tedious at the moment. This issue is being tracked here https://github.com/hirosystems/chainhook/issues/224 and we will be addressing it in the coming weeks.

**Comment by utibeabasi6** [comment]
hey @lgalabru @echoWeb3 by bitcoind node you mean a full bitcoin core node?
https://bitcoin.org/en/full-node#what-is-a-full-node

**Comment by lgalabru** [comment]
The documentation was updated and we do another pass using feedbacks in https://github.com/hirosystems/chainhook/issues/248.
