### ISSUE TITLE
The node does not have a listening port and has a panick issue

### ISSUE THREAD

**Issue by sundafa** [hirosystems/chainhook#268]
Initially normal, but after running for a period of time, it was all due to this error.

config.toml
```
[storage]
driver = "memory"
redis_uri = ""

[chainhooks]
max_stacks_registrations = 500
max_bitcoin_registrations = 500

[network]
mode = "mainnet"
bitcoind_rpc_url = "http://127.0.0.1:8332"
bitcoind_rpc_username = "uu1"
bitcoind_rpc_password = "iou1dq"
stacks_node_rpc_url = "http://127.0.0.1:20443"
```

run-cmd
`chainhook service start --config-path=./config.toml`

err-log
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` valuethread '', <unnamed>' panicked at 'components/chainhook-event-observer/src/hord/db/mod.rscalled `Option::unwrap()` on a `None` value:', 1230components/chainhook-event-observer/src/hord/db/mod.rs::361230
:36
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', components/chainhook-event-observer/src/hord/db/mod.rs:1230:36
```

**Comment by lgalabru** [comment]
This issue has been fixed in the latest version (v0.14). You'll need to pull the latest version of `main`, recompile, and migrate your config file using the latest syntax: https://github.com/hirosystems/chainhook/blob/develop/tests/Chainhook.toml
Feel free to re-open this issue if you're still experiencing this crash.
Thanks!
