### ISSUE TITLE
Optional fields are required to make bitcoin block, causing errors 

### ISSUE THREAD

**Issue by MicaiahReid** [hirosystems/chainhook#381]
**Describe the bug**
On [this line](https://github.com/hirosystems/chainhook/blob/499b86c9aac898257593bdd6c5cdf18fee0b1d87/components/chainhook-sdk/src/indexer/bitcoin/mod.rs#L461) when standardizing a bitcoin block, the `prevout` field for a bitcoin transaction is required, and Chainhook throws an error if the field is missing. However, `prevout` is an optional field, and many transaction inputs don't include it.

This causes many blocks to be skipped and will definitely lead to missed predicate triggers.

**To Reproduce**
1. Create and run the following predicate, and see that the transaction is not found.
```
{
  "uuid": "1",
  "name": "Hello Ordinals",
  "chain": "bitcoin",
  "version": 1,
  "networks": {
    "mainnet": {
      "start_block": 801221,
      "end_block": 801221,
      "if_this": {
        "scope": "txid",
        "equals": "0x55c86631e9b08b817e6ebac00b9818d1fd49e0a7d6c00429b6e364d3ef845920"
      },
      "then_that": {
        "file_append": {
          "path": "results/transaction-file-result.json"
        }
      }
    }
  }
}
```
**Expected behavior**
A bitcoin block is build event when optional transaction inputs are missing.

**Comment by qustavo** [comment]
AFAICT `prevout` is used to compute the fee https://github.com/hirosystems/chainhook/blob/499b86c9aac898257593bdd6c5cdf18fee0b1d87/components/chainhook-sdk/src/indexer/bitcoin/mod.rs#L493 and https://github.com/hirosystems/chainhook/blob/499b86c9aac898257593bdd6c5cdf18fee0b1d87/components/chainhook-sdk/src/indexer/bitcoin/mod.rs#L536.

I don't see where these are being used apart from just being set:
https://github.com/hirosystems/chainhook/blob/499b86c9aac898257593bdd6c5cdf18fee0b1d87/components/chainhook-sdk/src/indexer/bitcoin/mod.rs#L499-L500 

Since fees can be extracted from the block's RPC response, is removing `prevout` a possible solution here?

**Comment by MicaiahReid** [comment]
We actually found that it was the `is_coinbase` function that's broken. [This PR](https://github.com/hirosystems/chainhook/pull/391) will fix it.

All transactions except coinbase transactions must have a prevout field, so it's okay to require them.

**Comment by qustavo** [comment]
that makes sense!

**Comment by qustavo** [comment]
@MicaiahReid I noticed that the `prevout` field has been added to bitcoind on version [`v23.0.0`](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-23.0.md#updated-rpcs), meaning that previous versions will not have such a field populated. Would it make sense to validate the node's version upon chainhook start?

**Comment by MicaiahReid** [comment]
@qustavo great find. There's additional discussion here: https://github.com/hirosystems/chainhook/pull/391#issuecomment-1692368835
