### ISSUE TITLE
Identify mission critical threads, and force process termination when they crash

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/chainhook#517]
In addition to fixing bug when they are being experienced, we should make a pass on the sensitive crashing threads.
Certain threads are not mission critical, others are. when a mission critical thread crash, we should terminate the node, to attempt a recovery by reboot - most of the time, chainhook is able to recover from a reboot.

**Comment by MicaiahReid** [comment]
Here are Chainhooks threads/processes, the process' parent, it's expected behavior on failure, and whether Chainhook is currently executing that expected behavior. It seems we have a lot of mission critical threads that don't actually force process termination.

@lgalabru This table is just my opinion on what threads are "mission critical" (those that should force a restart of the whole process on fail, aka those marked "Crash" below). Lmk if you disagree on any of these.
| Parent | Thread/Process | On Fail Expected | Currently Working? |
| -------------- | ------ | ---------------- | ------ |
|  | main | crash | ✔️ |
| main | download tsv | Crash  | ✔️ |
| main | stx scan runloop | Crash | ❌ |
| main | btc scan runloop | Crash | ❌ |
| main | predicate API server | Crash | ❌ |
| main | event observer | Crash | ❌ |
| main | observer event loop | Crash | ✔️ |
| stx scan runloop | individual stx scan | Error | ✔️ |
| btc scan runloop | individual btc scan | Error | ✔️ |
| event observer | observer cmds runloop | Crash | ❌ |
| observer cmds loop | ProcessBitcoinBlock | Crash | ❌ |
| observer cmds loop | PropagateBitcoinChainEvent  | Update predicate status interrupted | ❌ |
| observer cmds loop | PropagateStacksChainEvent  | Update predicate status interrupted | ❌ |
| observer cmds loop | RegisterPredicate  | Error | ✔️ |
| observer cmds loop | Deregister/Expire Predicates  | Warn | N/A (will not fail) |
| event observer | event ingestion server | Crash | ❌ |
| event observer | prometheus monitoring thread | Error | ✔️ |
| observer event loop | PredicateRegistered | Warn? | ❌ |
| observer event loop | PredicateEnabled | Warn? | ❌ |
| observer event loop | PredicateDeregistered | Warn? | ❌ |
| observer event loop | BitcoinChainEvent | Warn? | ❌ |
| observer event loop | StacksChainEvent | Warn? | ❌ |
